### ISSUE TITLE
Recognition of Lecanopteris sensu lato (Polypodiaceae) [NOT PASSED]

### ISSUE THREAD

**Issue by DrAshleyField** [pteridogroup/ppg#28]
### Author(s) of proposal

Ashley Field

### Name of taxon

Lecanopteris Reinw.

### Rank of taxon

Genus

### Approximate number of species affected

12

### Description of change

[Perrie et al. (2021)](https://doi.org/10.3767/blumea.2021.66.03.07) re-circumscribed the genus _Lecanopteris_ Reinw. based on a further morphological and philosophical appraisal of the phylogenies of [Testo et al. (2019)](https://doi.org/10.1600/036364419X15650157948607) and [Chen et al. (2020)](https://doi.org/10.1016/j.ympev.2019.106665). _Lecanopteris_ was broadened to include the recently resurrected and recircumscribed genus _Dendroconche_ and recently described genus _Zealandia_ to achieve monophyly from a previously paraphyletic _Microsorum_ and _Colysis_. The abstract of [Perrie et al. (2021)](https://doi.org/10.3767/blumea.2021.66.03.07) is reproduced below:

"The fern genus _Microsorum_ is not monophyletic, with previous phylogenetic analyses finding three lineages to group not with the type species, but to form a grade related to the 13 species of _Lecanopteris_. These three lineages have recently been recognised as separate genera: _Bosmania_, _Dendroconche_, and _Zealandia_. Here, we explore the morphological characterisation of _Lecanopteris_ and these other three lecanopteroid genera. While the\ traditional circumscription of _Lecanopteris_ has seemed sacrosanct, its defining morphological character states of rhizome cavities and ant brooding associations occur in other lecanopteroid ferns and elsewhere in the Polypodiaceae. Instead, we suggest that the morphological characterisation of an expanded _Lecanopteris_ including the _Dendroconche_ and _Zealandia_ lineages is just as good, if not better, with the pertinent character states being the absence of sclerenchyma strands in the rhizome and at least some fronds having Nooteboom's type 5 venation pattern. This wider circumscription is also better able to accommodate phylogenetic uncertainty, and it means that groups of species traditionally placed together in a single genus are not distributed across different genera. General users familiar with the narrower circumscription of _Lecanopteris_ will not be significantly disrupted, because there is little geographic overlap with the lineages added to the genus. Consequently, we make new combinations in _Lecanopteris_ for 11 species and one subspecies."

### Reason for change

Multiple studies have shown that _Microsorum_ and _Colysis_ as adopted in PPG I (2016) were paraphyletic. This proposal is directed at achieving monophyly among relevant genera by recognition a broadly circumscribed _Lecanopteris_ subsuming the recently described _Dendroconche_ and _Zealandia_ but not _Bosmania_. This proposal should be read in conjunction with proposals for _Bosmania_ + _Dendroconche_ + _Lecanopteris s.s._ + _Zealandia_ sensu [Testo et al. (2019)](https://doi.org/10.1600/036364419X15650157948607) (#25, #26, #27).

This proposal affects approximately 12 species occurring across Oceania. It was adopted [World Ferns](https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list#plantUid-9359). It should be compared to the contrasting three-genus classification presented by [Testo et al. (2019)](https://doi.org/10.1600/036364419X15650157948607).

### Reference(s) for publication of the name

Perrie L.R., Field A.R., Ohlsen D.J., Brownsey P.J. (2021) Expansion of the fern genus Lecanopteris to encompass some species previously included in Microsorum and Colysis (Polypodiaceae) Blumea 66: 242–248.

See also:

Chen C-C, Hyvönen J, Schneider H. 2020. Exploring phylogeny of the microsoroid ferns (Polypodiaceae) based on six plastid DNA markers. Molecular Phylogenetics and Evolution 143: 106665.

Testo W.L., Field A.R., Sessa E.B., Sundue M. (2019) Phylogenetic and Morphological Analyses Support the Resurrection of Dendroconche and the Recognition of Two New Genera in Polypodiaceae Subfamily Microsoroideae Systematic Botany 44(4): 1–16.

### List the numbers of any related issues

#25, #26, #27

### Code of Conduct

- [X] I agree to follow the PPG Code of Conduct

**Comment by wtesto** [comment]
I wish to weigh in on this proposal, as I am one of the folks responsible for the recognition of _Zealandia_ and the resurrection of _Dendroconche_, both of which would be treated within _Lecanopteris_. if this proposal were accepted. 

The non-monophyly of _Microsorum_ and several related genera is well-documented (Kreier et al., 2008; Testo & Sundue, 2014; Chen et al., 2020) and has stymied efforts to produce a satisfactory generic level classification of Polypodiaceae subfamily Microsoroideae. Testo et al. (2019) generated a phylogeny of subfamily Microsoroideae using four chloroplast loci and 167 taxa – including the type species of all 12 genera recognized by PPG1 (2016) for the subfamily – and demonstrated that 16 taxa that had treated as _Microsorum_ and _Colysis_ were not closely related to those genera and instead formed three monophyletic groups that were successively sister to _Lecanopteris_. Using ancestral character state reconstruction of six morphological characters, Testo et al. (2019) demonstrated that each of the three groups presented readily evident synapomorphies and all of them could be easily distinguished from each other and from _Lecanopteris_. We recognized these three clades at the generic level – one name (_Dendroconche_) was resurrected from synonymy, and two others (_Bosmania_ and _Zealandia_) were newly described. 

As thus circumscribed, the four genera of lecanopteroid ferns (tribe Lecanoptereae C.C. Chen & H. Schneider) are:

_Lecanopteris_, characterized by an association with ants that live in cavities either within or underneath dramatically enlarged rhizomes.

_Dendroconche_, characterized by hemiepiphytic growth habit, non-pruinose rhizomes, non-impressed sori, bright yellow verrucate spores, and specialized laterally inserted clasping roots used for climbing.

_Zealandia_, characterized by (mostly) epiphytic growth habit, deeply impressed sori that are readily visible on the adaxial laminar surface, prominent veins that contrast strongly with the laminar tissue, and pruinose rhizomes. 

_Bosmania_, characterized by terrestrial growth habit, membranaceous laminae, and simple leaves that are deciduous in the dry season. 


These synapomorphies are supported by ancestral character state reconstructions and images are provided to guide users. 

<img width="584" alt="Screen Shot 2023-08-20 at 1 18 37 PM" src="https://github.com/pteridogroup/ppg/assets/63684485/265eaa1e-7a7f-4ab5-b845-ab1804b224ee">

The monophyly of these genera was supported by a subsequent study (Chen et al. 2020) with improved taxon sampling and a different set of loci, though that study recovered _Dendroconche_ (vs. _Zealandia_ in Testo et al. 2019) as sister to _Lecanopteris_. Chen et al. (2020) compared the generic classification proposed by Testo et al. (2019) to two alternatives involving a more broadly construed _Lecanopteris_; they concluded that extending _Lecanopteris_ to include _Dendroconche_ was “less suitable” than recognizing the latter as a distinct genus and that recognizing _Lecanopteris_ with _Dendroconche_ and _Zealandia_ included in it “would still perhaps not be the best option because it would be morphologically poorly defined.” 

As proposal #28 shows, Perrie et al. (2021) rejected the recognition of _Zealandia_ and _Dendroconche_ in favor of an expanded _Lecanopteris_ that includes those taxa. Here, I will outline the main arguments presented by Perrie et al. (2021) for expanding _Lecanopteris_ and explain why I think recognition of four genera within Tribe Lecanoptereae is preferable. 

**Utility and stability of genus-level synapomorphies:**  Perrie et al. (2021) suggests that “the morphological characterisation of an expanded _Lecanopteris_ including the _Dendroconche_ and _Zealandia_ lineages is just as good, if not better, with the pertinent character states being the absence of sclerenchyma strands in the rhizome and at least some of the fronds having Nooteboom’s type 5 venation pattern.”

With the exception of _Zealandia powelii_, all of the species included in _Lecanopteris_ by Perrie et al. (2021) lack free sclerenchyma strands in the rhizome, though many of these species do possess sclerenchyma bands associated with the rhizome vasculature (Bosman, 1991; Nooteboom, 1997; Testo & Sundue, 2014). In addition, and as pointed out by Perrie et al. (2021), numerous taxa that belong to non-lecanopteroid lineages in subfamily Microsoroideae also lack sclerenchyma strands in the rhizome, including species of _Microsorum_, _Lepidomicrosorium_, _Neocheiropteris_, and several unplaced taxa.

Further, the type 5 venation pattern of Nooteboom (1997) is not present in all species included in Perrie et al.’s concept of _Lecanopteris_ (_Zealandia powellii_ lacks such venation) and is only present in the fertile leaves of what is by far the most commonly collected species in the clade (_Zealandia pustulata_). They also report that “type 5 patterns were recorded for several species currently unplaced phylogenetically but which may be lecanopteroids.” This includes _Microsorum aurantiacum_, which was suggested by Nooteboom (1997) to be a close relative of taxa now placed in _Zealandia_, but which possesses sclerenchyma strands in the rhizome, thereby presenting another potential exception to the characters used by Perrie et al. (2021) to support an expanded _Lecanopteris_.  

<img width="541" alt="Screen Shot 2023-08-20 at 9 07 52 AM" src="https://github.com/pteridogroup/ppg/assets/63684485/065f14d3-b52e-4e57-ac41-b39248c3152c">

The above is Figure 2 from Perrie et al. (2021), which shows (from left to right) venation types 5, 3, and 1 of Nooteboom (1997). In my view, the differences between these venation types are subtle and considerably more challenging to interpret than the characters proposed by Testo et al. (2019) as synapomorphies for the genera recognized therein. 

With character stability set aside, I do not agree with Perrie et al.’s claim that “the morphological characterisation of an expanded Lecanopteris including the Dendroconche and Zealandia lineages is just as good, if not better,”than the traditional circumscription of the genus on the basis of myrmecophily and highly modified rhizomes, like these (photo by Chuck Hung, used under CC BY-NC-SA license): 

![lecanopteris_rhizome](https://github.com/pteridogroup/ppg/assets/63684485/abcdbd79-76dd-44c1-9c44-89375cb74903)

Perrie et al. (2021) also argue that myrmecophily and rhizomes with ant domatia are not suitable synapomorphies for _Lecanopteris_, as they occur in other genera of Polypodiaceae. They do not, however, apply the same logic to the presence of sclerenchyma strands in the rhizome or reticulate venation with large costal areoles, the characters they use to define the genus. Both characters occur in many genera of Polypodiaceae and other fern families and are doubtlessly much more homoplastic than than ant-fern symbiosis like that found in _Lecanopteris_. 

Setting this point aside, both the classification schemes of Testo et al. (2019) and Perrie et al. (2021) utilize some synapomorphies that are not unambiguous (i.e. those character states are not shared by all members of the genus or they occur in other clades); this is certainly not unique to this group of ferns. In such a case, having a greater number of characters that together define clades –like the classification of Testo et al. (2019)-- is clearly preferable. This approach to classifying the lecanopteroid ferns promotes recognition of genera that are more morphologically cohesive, share a larger number of evident synapomorphies, and maintains the long-standing circumscription of _Lecanopteris_, one of the most distinctive Polypodiaceae genera. 


**Stability in the face of phylogenetic uncertainty:**

Perrie et al. (2021) argue that an expanded _Lecanopteris_ is better suited than the classification proposed by Testo et al. (2019) to accommodate phylogenetic uncertainty in the microsoroid ferns. This uncertainty is problematic in part, they suggest, because Testo et al. (2019) and Chen et al. (2020) recovered different phylogenetic relationships for the genera in tribe Lecanoptereae, and Perrie et al. (2021) depict the relationships of _Dendroconche_, _Zealandia_, and _Lecanopteris_ with a polytomy (Figure 1). Though Testo et al. (2019) and Chen et al. (2020) do differ in the clade they recover as sister to _Lecanopteris_, neither study recovers a polytomy, and all the genera proposed by Testo et al. (2019) are strongly supported as monophyletic in all analyses conducted by both Testo et al. (2019) and Chen et al. (2020).

Following up on this, Perrie et al. (2021) point to numerous species currently treated in _Microsorum_ that have not been placed in a phylogenetic context and may eventually be found to be members of tribe Lecanoptereae. They state that “if any of the unplaced species did not fall within the already identified lineages (as happened within this geographic region for some New Caledonian _Lastreopsis_; Gardner et al. 2017), then additional genera would be required.*** While that could happen at some point in the future, I do not agree that such a possibility is “arguably a significant problem,” as Perrie et al. (2021) posit. Such discoveries have improved our understanding of fern evolution and informed classification efforts, whether they have ultimately led to an increase (e.g. dissolution of _Blechnum_ s.l.; Perrie et al. 2014; Gasper et al. 2017) or a decrease (e.g. union of _Eriosorus_ and _Jamesonia_; Sánchez-Baracaldo 2004) in the number of recognized genera.  

***A brief aside – the Lastreopsis taxa mentioned were found both by Gardner et al. (2017) and Perrie et al. (2021b) to be clearly nested within Lastreopsis, and no new genus name was ever proposed to accommodate them. I point this out as it is relevant to this and possibly to future proposals. 

Testo et al. (2019), Chen et al. (2020), and Perrie et al. (2021) all concur that data available at this time are not sufficient to confidently assign these unplaced species to the genera defined by Testo et al. (2019), other lineages within the lecanopteroid ferns, or to another clade of subfamily Microsoroideae altogether. I think that is OK. As I see it, decisions about generic classification should be made based on available data, and generic circumscriptions can (and should) be re-evaluated as new data become available. 


**Regional versus global perspectives on fern classification:** 

Perrie et al.’s argument for expanding _Lecanopteris_ to include _Zealandia_ and _Dendroconche_ is based in part on the premise that these lineages rarely overlap geographically, thereby minimizing disruption and confusion for workers in a given country or region. As I understand it, this point argues that the disruption of the traditional circumscription of _Lecanopteris_ at a global scale will not significantly impact a worker based in New Zealand, for example, because they previously did not have any _Lecanopteris_ species in their flora, so they have a “fresh slate”, so to speak. Similarly, someone working in Malaysia would not be seriously inconvenienced, Perrie et al. argue, because all but one of the species of a newly expanded _Lecanopteris_ in their flora had been treated in that genus already. 

While I do not agree with Perrie et al.’s point that it is inconsequential to lump readily distinguishable groups because workers in one region or another may not notice much of a difference (in that case, why not re-circumscribe _Salpichlaena_ to include _Stenochlaena_ and _Telmatoblechnum_?), I think that is is more important to note that such a viewpoint appears to be incompatible with the goals of PPG2. Attempts at developing coherent classifications for ferns in the modern era (e.g., Smith et al., 2006; Christenhusz & Chase, 2014; PPG1, 2016) have had a global scope, and PPG2 is no exception. PPG2 is a global community effort includes nearly 200 participants from dozens of countries, and there is good reason to expect that the classification we develop will be widely adopted by users from around the world for applications that are often global in scope. Of course, some users may opt for alternative classifications that are framed by regional or national perspectives on plant diversity; nonetheless, I do not think such views should inform the PPG2 approach to classification. 

For these reasons, I will be voting against the recognition of an expanded _Lecanopteris_ and in favor of the recognition of _Bosmania_(#27), _Dendroconche_(#27), and _Zealandia_(#26). 

-- Wes Testo




**References**

Bosman, M. T. M. 1991. A monograph of the fern genus _Microsorum_ (Polypodiaceae) including an attempt towards a reconstruction of the phylogenetic history of the microsoroids. Leiden Botanical Series, 14: 1–161.

Chen C-C, Hyvönen J, Schneider H. 2020. Exploring phylogeny of the microsoroid ferns (Polypodiaceae) based on six plastid DNA markers. Molecular Phylogenetics and Evolution 143: 106665.

Christenhusz, M. J., & Chase, M. W. 2014. Trends and concepts in fern classification. Annals of botany, 113: 571–594.

Gardner, J. J., Perrie, L., Shepherd, L., & Nagalingum, N. S. 2017. Taxonomic placement of unassigned species of lastreopsid ferns (Dryopteridaceae) using phylogeny. Systematic Botany 42: 385–391.

de Gasper, A. L., Almeida, T. E., Dittrich, V. A. D. O., Smith, A. R., & Salino, A. 2017. Molecular phylogeny of the fern family Blechnaceae (Polypodiales) with a revised genus‐level treatment. Cladistics, 33: 429–446.

Kreier, H. P., Zhang, X. C., Muth, H., & Schneider, H. 2008. The microsoroid ferns: Inferring the relationships of a highly diverse lineage of Paleotropical epiphytic ferns (Polypodiaceae, Polypodiopsida). Molecular Phylogenetics and Evolution, 48: 1155–1167.

Nooteboom, H. P. 1997. The microsoroid ferns (Polypodiaceae). Blumea: Biodiversity, Evolution and Biogeography of Plants, 42: 261–395.

Perrie, L. R., Wilson, R. K., Shepherd, L. D., Ohlsen, D. J., Batty, E. L., Brownsey, P. J., & Bayly, M. J. 2014. Molecular phylogenetics and generic taxonomy of Blechnaceae ferns. Taxon, 63: 745–758.

Perrie L.R., Field A.R., Ohlsen D.J., Brownsey P.J. (2021) Expansion of the fern genus Lecanopteris to encompass some species previously included in Microsorum and Colysis (Polypodiaceae) Blumea 66: 242–248.

Perrie, L. R., Amice, R., Shepherd, L. D., & Brownsey, P. J. (2021B). _Lastreopsis abscondita_ (Dryopteridaceae), a new fern species endemic to New Caledonia. New Zealand Journal of Botany, 59(3), 409-422.

PPG 1. 2016. A community‐derived classification for extant lycophytes and ferns. Journal of systematics and evolution, 54: 563–603.

Sánchez‐Baracaldo, P. 2004. Phylogenetics and biogeography of the neotropical fern genera _Jamesonia_ and _Eriosorus_ (Pteridaceae). American Journal of Botany, 91: 274–284.

Smith, A. R., Pryer, K. M., Schuettpelz, E., Korall, P., Schneider, H., & Wolf, P. G. 2006. A classification for extant ferns. Taxon, 55: 705–731.
 
Testo W.L., Field A.R., Sessa E.B., Sundue M. (2019) Phylogenetic and Morphological Analyses Support the Resurrection of _Dendroconche_ and the Recognition of Two New Genera in Polypodiaceae Subfamily Microsoroideae Systematic Botany 44(4): 1–16.

**Comment by leonperrie** [comment]
The lecanopteroid ferns are a tricky situation, perhaps explaining why there was no action for 15 years after their non-monophyly with respect to _Microsorum_ was first detected.  The two principal solutions of [1] recognising several, small, genera (i.e., _Bosmania_, _Dendroconche_, and _Zealandia_) or [2] expanding _Lecanopteris_ both have disadvantages (as well as merits).  We prefer the expansion of _Lecanopteris_, which is why we offered it for consideration (Perrie et al. 2021) – it is for us the “least worst” of two unpalatable options.

The principal disadvantage of expanding the circumscription of _Lecanopteris_ is that even more morphological variation is encompassed.  But it's important context that one of the species of _Lecanopteris_ s.s. does not form rhizome cavities, and some of the species of the _Dendroconche_ lineage seem to be associated with ants, meaning that the traditional circumscription of _Lecanopteris_ is ‘fuzzier’ than usually portrayed.  The characters in this broader group of ferns are unfortunately rarely perfectly diagnostic, including those suggested for the segregates.  Leaf venation may be subtle to some, but, speaking from personal field experience of these ferns, so are several of the characters proffered for the segregates.

At issue is not whether the geographic focus of PPG should be anything but global, but rather whether it is primarily for taxonomists or for general users of taxonomic names.  There are a lot more of the latter, and there is an argument for prioritising their needs (albeit within a monophyletic classification) over what might be a taxonomist’s desire to have genera that are globally morphologically cohesive.  

In this regard, expanding _Lecanopteris_ keeps together several species that have long been congeneric (albeit in different genera) rather than disassociating them across a couple of genera (i.e., _Dendroconche_ and _Zealandia_ for several Australian, New Caledonian, and New Zealand examples).  The surveying I’ve done, albeit admittedly limited, anecdotal, and only in New Zealand, indicates a clear preference among general users for keeping the relevant species in one genus (which would mean adopting an expanded _Lecanopteris_).  

There are consequences for general users in the regions with _Lecanopteris_ s.s. in that three species would be added within their regions if its circumscription was expanded, with one of these species being widespread (but little observed – just two observers on iNaturalist for these three species even though there are tens of thousands of users of this citizen science platform in these regions).  Weighing impacts on general users across regions is invidious, but a name change is needed for these species regardless (whether it be to _Dendroconche_ or _Lecanopteris_).  General taxonomy users familiar with _Lecanopteris_ s.s. already need to deal with its morphological variability, such that accommodating another species (or three species for those in New Guinea) within its circumscription is unlikely to be overly problematic for regional identification keys, and means dealing with one less genus name.

A second advantage of an expanded _Lecanopteris_ is that a broader genus can more easily and stably accommodate the uncertain relationships of several species.  As these are tested with DNA analyses, there is every possibility that they will fall outside the _Dendroconche_, _Zealandia_, and _Bosmania_ (and _Lecanopteris_ s.s.) lineages.  If so, they could easily be accommodated within an expanded _Lecanopteris_ circumscription, but, under the segregated system, they would necessitate the description of additional genera that would be similarly small (likely one to a few species).  Preserving _Lecanopteris_ s.s. could well entail recognising more genera than just the three additions already posited.

Perhaps it’s only a matter of taste as to whether one prefers fewer, bigger, more stable genera or smaller genera that have a propensity to proliferate as we learn more about evolutionary relationships – splitting in the face of phylogenetic uncertainty tends to beget more splitting.  General users typically prefer stability and fewer (generic) names.  


*** with the aside about _Lastreopsis_, it’s less about the genus circumscription (although note the support values in Gardner at al. 2016), and more about it being unclear to which of the two subgenera the New Caledonian species should be assigned.  The point that is relevant to the lecanopteroids is that it is not unusual to find lineages even in the Pacific that don’t fit comfortably with patterns determined elsewhere/previously.



Gardner JJ, Perrie L, Shepherd L, Nagalingum NS. 2017. Taxonomic placement of unassigned species of lastreopsid ferns (Dryopteridaceae) using phylogeny. Systematic Botany 42: 385–391.

Perrie LR, Field AR, Ohlsen DJ, Brownsey PJ. 2021 Expansion of the fern genus Lecanopteris to encompass some species previously included in Microsorum and Colysis (Polypodiaceae) Blumea 66: 242–248.

**Comment by joelnitta** [comment]
This proposal was voted on during PPG Ballot 3 (voting period September 2023). A total of 68 votes were cast. There were 34 'Yes' votes (50%) and 34 'No' votes (50%). The proposal does not pass.
